#! /usr/bin/env python

'''
Browse Indico from the command line
'''

import sys
import os
import argparse
import time
import subprocess
import json
import hmac
import hashlib
import urllib
import yaml
import requests

PURPLE      = '\033[95m'    # pylint: disable=anomalous-backslash-in-string
BLUE        = '\033[94m'    # pylint: disable=anomalous-backslash-in-string
GREEN       = '\033[92m'    # pylint: disable=anomalous-backslash-in-string
YELLOW      = '\033[93m'    # pylint: disable=anomalous-backslash-in-string
RED         = '\033[91m'    # pylint: disable=anomalous-backslash-in-string
BOLD        = '\033[1m'     # pylint: disable=anomalous-backslash-in-string
UNDERLINE   = '\033[4m'     # pylint: disable=anomalous-backslash-in-string
ENDC        = '\033[0m'     # pylint: disable=anomalous-backslash-in-string

def parsedate(string):
    '''
    Parse date with date command
    '''

    proc = subprocess.Popen(
        ['date', '-d', string, '+%Y-%m-%d'],
        stdout=subprocess.PIPE,
    )
    return proc.communicate()[0]

def downloadall(cfg, results, since, cat):
    '''
    Download all material
    '''

    for result in results:
        if not since or result['startDate']['date'] > since:
            print '%s%s%s, %s%s%s' % (
                PURPLE,
                result['title'],
                ENDC,
                GREEN,
                result['startDate']['date'],
                ENDC,
            )
            try:
                downloads = '%s/%s/%s' % (cfg['downloads'], cat, result['id'])
                os.makedirs(downloads)
            except OSError:
                pass
            for folder in result['folders']:
                for attachment in folder['attachments']:
                    outpath = '%s/%s' % (downloads, attachment['filename'])
                    print "\tWriting %s" % outpath
                    download(
                        cfg,
                        result['id'],
                        folder['id'],
                        attachment['id'],
                        outpath,
                    )

def get(cfg, path):
    '''
    Sign URL and get
    '''

    params = [
        ('apikey', cfg['token']),
        ('timestamp', int(time.time())),
    ]
    sign = hmac.new(
        cfg['secret'],
        '%s?%s' % (path, urllib.urlencode(params)),
        hashlib.sha1).hexdigest()
    params.append(('signature', sign))
    url = '%s%s?%s' % (
        cfg['server'],
        path,
        urllib.urlencode(params),
    )
    return requests.get(url)

def download(cfg, event, material, resource, outpath):
    '''
    Download material
    '''

    path = '/export/event/%s/material/%s/%s.bin' % (
        event,
        material,
        resource,
    )
    
    if os.path.exists(outpath):
        print >> sys.stderr, "\t%s%s already exists%s" % (
            RED,
            outpath,
            ENDC,
        )
    else:
        with open(outpath, 'w') as fhl:
            print >> fhl, get(cfg, path).content


def lscat(cfg, cat, verbose):
    '''
    List category
    '''

    path = '/export/categ/%d.json' % cat
    content = get(cfg, path).json()
    if verbose:
        print json.dumps(content, indent=1)
    return content['results']


def main():
    '''
    Parse arguments and config
    '''

    # Parse arguments
    parser = argparse.ArgumentParser(
        description='Browse Indico from the command line.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        '-d',
        '--directory',
        help="Indicolite directory",
        default='~/.indicolite',
    )
    parser.add_argument(
        '-v',
        '--verbose',
        help="print JSON output",
        action='store_true',
    )
    args = parser.parse_args()

    # Load config
    with open(os.path.expanduser(args.directory + '/cfg.yaml')) as fhl:
        cfg = yaml.load(fhl)

    # Parse date
    if cfg['since']:
        since = parsedate(cfg['since'])
        if not since:
            return 1
    else:
        since = None

    # Query
    for cat in cfg['categories']:
        results = lscat(cfg, cfg['categories'][cat], args.verbose)

        # Report
        downloadall(cfg, results, since, cat)

if __name__ == '__main__':
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        pass
