.TH "INDICOLITE" "1" "September 2016" "" ""
.hy
.SH NAME
.PP
indicolite \[en] Browse Indico from the command line
.SH SYNOPSIS
.PP
See \f[B]indicolite \-h\f[].
.SH DESCRIPTION
.PP
Download all material from a list of categories.
.SH CONFIGURATION FILE
.PP
Indicolite mostly operates from a configuration files which looks like
this:
.IP
.nf
\f[C]
server:\ \[aq]https://indico.yoursite.net\[aq]
secret:\ \[aq]00000000\-0000\-0000\-0000\-000000000000\[aq]
token:\ \[aq]11111111\-1111\-1111\-1111\-111111111111\[aq]

downloads:\ \[aq]path/to/directory\[aq]
since:\ \[aq]18\ April\ 2016\[aq]
categories:
\ \ \ \ foo:\ 1111
\ \ \ \ bar:\ 2222
\ \ \ \ baz:\ 3333
\ \ \ \ boo:\ 4444
warnexist:\ true
\f[]
.fi
.SH AUTHORS
Jérôme Belleman.
